blank_issues_enabled: false
contact_links:
  - name: 🧑‍💻 Dantotsu Help on Discord
    url: https://discord.com/invite/4HPZ5nAWwM
    about: Get support, ask questions, and join the community discussions.

  - name: 📱 Dantotsu Help on Telegram
    url: https://t.me/dantotsuapp
    about: Connect with the community, ask questions, and get help directly on Telegram.
